### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by nfearnley** [maximilionus/python_docs_dark#1]
You cannot install this using only the Stylish extension. You must also have the Stylus extension installed. Please update your documentation according to avoid frustrating users in the future.

**Comment by maximilionus** [comment]
Stylus extension is not required for this theme, you can freely install usercss directly to Stylish

**Comment by maximilionus** [comment]
Turns out you were right 😅. I made a mistake with required extensions. `Stylish` extension is not even necessary *(Not even sure why i made it required)*, only `Stylus` is required for theme to be installed. I'm gonna fix this asap. Thanks for the report and sorry that this took so much time for me to realize it.
